name: nouns_sdk
description: Providing NounsDAO addresses, etc.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
# dependencies:
#   equatable: ^2.0.3
#   json_annotation: ^4.0.1

# dev_dependencies:
#   build_runner: ^2.1.2
#   json_serializable: ^5.0.0
#   test: ^1.17.0
