version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "chat"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-kqjxmceuuf1l"
s3_prefix = "chat"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TableName=\"simplechat_connections\""
image_repositories = []
