version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nouns"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-kqjxmceuuf1l"
s3_prefix = "nouns"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SocketTableName=\"nouns_websocket_connections\""
image_repositories = []
